apiVersion: v1
kind: Secret
metadata:
  name: identity-secrets
type: Opaque
stringData:
  ConnectionStrings__DockerTestContextConnection: "Server=sqlserver;Database=DockerTest;User Id=sa;Password=P@ssw0rd12345!;TrustServerCertificate=True;MultipleActiveResultSets=true"
  Redis__Connection: "redis:6379"