apiVersion: apps/v1
kind: Deployment
metadata:
  name: dockertest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dokertest
  template:
    metadata:
      labels:
        app: dokertest
    spec:
      containers:
      - name: dockertest123
        image: ibrahimfarag123/dockertest
        ports:
        - containerPort: 80
        envFrom:
        - secretRef:
            name: identity-secrets
        readinessProbe:
          httpGet:
            path: /health
            port: 80
            scheme: HTTP
