apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: identity-ingress
spec:
  rules:
  - host: auth.company.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: dockertest
            port:
              number: 80